rm(list=ls())
dev.off(dev.list()["RStudioGD"])
setwd("C:/Users/Farzad/Dropbox/Data Science Toolbox/Course 4/Week1/ExData_Plotting1")
D = read.csv("household_power_consumption.txt", sep=";",na.strings = "?", colClasses = c("factor","factor","numeric","numeric","numeric","numeric","numeric","numeric","numeric"))
D = D[D$Date =="1/2/2007"|D$Date =="2/2/2007",]
D$DT = strptime(paste(D$Date, D$Time), format="%d/%m/%Y %H:%M:%S")
png("Plot3.png", width = 480, height = 480, units = "px")
plot(D$DT,Sub_metering_1,type = "l", ylab = "Energy sub metering",xlab = "" )
lines(D$DT,Sub_metering_2,col = "red")
lines(D$DT,Sub_metering_3,col = "blue")
legend("topright",legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),pch = "_", col = c("black","red","blue"))
dev.off()